services:
  rekas-fe:
    build:
      context: .
      args:
        # --- MASUKKAN ALAMAT API ASLI DI SINI ---
        # Jangan pakai localhost. Pakai domain backendmu (HTTPS).
        # Contoh: https://rekas.geocitra.com
        - VITE_API_URL=https://rekas.geocitra.com
    container_name: rekas-fe
    restart: always
    networks:
      - e-daily-report-net

networks:
  e-daily-report-net:
    external: true
    name: e-daily-report_default
